import type { Metadata } from "next";
import "./globals.css";
import NavBar from "@/components/layout/navbar";
import { Suspense } from "react";
import {poppins, ayrRounded} from "@/fonts";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${poppins.variable} ${ayrRounded.variable}`}>
      <body>
        <NavBar />
        <Suspense><main>{children}</main></Suspense>
      </body>
    </html>
  );
}
